### PR TITLE
[NAVAJO-4] Frequency Chart

### LINKED ISSUE #4: Build frequency chart component
[UX Mock](https://xd.adobe.com/view/7381a2ce-405a-47fd-970c-3a66591692e3/screen/e60cee43-ef60-45f2-a9e9-ad6eb8ce5191/frequency)

- [ ] Create necessary component(s) and incorporate d3
- [ ] Maybe investigate using wrappers around d3 to make implementation easier (example [vue-c3](https://github.com/chryb/vue-c3))
- [ ] Tests

### PR DESCRIPTION
**Pull request by Jbcampbe**
Closes #4 

I will fix some of the styling and update this PR but since it is functionally complete I am putting it up so you can review whenever. Probably won't get to styling it for another couple days

### CODE REVIEW

**Comment by Jbcampbe** [comment]
Ready For Review

**Comment by Jbcampbe** [comment]
This PR feels very sad and lonely... and neglected.... and needing love...

**Comment by amenders** [comment]
screen shot 2018-04-08 at 2 30 36 pm
Can we make the tab-bar height a percentage or somehow avoid this situation? This at the standard window size on my machine.

**Review by amenders — APPROVED** [review]
Pulled, tested, loved.

**Pull request merged**
