### PR TITLE
[NAVAJO-8, NAVAJO-9] Anagram and Transposition component

### LINKED ISSUE #8: Complete Anagram Component
Initial Creation Handled in #5. This is the work needed to complete the component

[UX Mock](https://xd.adobe.com/view/7381a2ce-405a-47fd-970c-3a66591692e3/screen/13ceccb5-ea31-4752-8e1e-dc3cbce0b01a/anagram-main)

- [x] Anagram Solver

### LINKED ISSUE #9: Complete Columnar Transposition Component
Initial Creation Handled in #5. This is the work needed to complete the component

[UX Mock](https://xd.adobe.com/view/7381a2ce-405a-47fd-970c-3a66591692e3/screen/fe01441c-5344-413d-a3d6-16ab72e8e848/columnar-main)

- [x] Transposition solver

### PR DESCRIPTION
**Pull request by Jbcampbe**
Closes #8 
Closes #9 

Still needs a little styling help with the arrows. Couldn't figure out how to get them to look right

### CODE REVIEW

**Comment by amenders** [comment]
screen shot 2018-03-23 at 3 52 50 pm
I don't believe that this should be happening...

**Comment by Jbcampbe** [comment]
@amenders I figured out the problem. That actually is expected behavior. Since we are decrypting instead of encrypting the process works backward

**Comment by amenders** [comment]
screen shot 2018-03-23 at 11 40 43 pm
It looks like we're not stripping out the spaces?

**Comment by Jbcampbe** [comment]
I've got that on #14

**Comment by amenders** [comment]
The UI currently doesn't really support a block size of more than 7, and small window sizes do not go over 6; do we have a plan for this?

**Comment by Jbcampbe** [comment]
> The UI currently doesn't really support a block size of more than 7, and small window sizes do not go over 6; do we have a plan for this?

Ummm. I don't know. I guess we should probably support larger block sizes... How would we handle it? Just wrap and create another row?

**Review by amenders — APPROVED** [review]
As a side note, I would be really interested to know how hard it would be to add animations of the blocks sliding as a user changes their position. : ) not to worry about now...

**Comment by Jbcampbe** [comment]
Feel free to create a ticket : )

**Pull request merged**
